directory:
    temp: s:/WFP/MODIS/Scratch
    GDAL: "C:/Program Files/GDAL/"

EXTRACT:
    directory:
        GDAL: "C:/Program Files/GDAL/"

MODIS:
    filenames:
        prefix: MOD13Q1
        extension: .hdf
        output: idn_phy_
        output_ext: .tif
    directory:
        tools: "s:/WFP/MODIS/MODIS Reprojection Tool/win/bin/"
        working: s:/WFP/MODIS/16Day/wfpdata/
        output_mosaic: s:/WFP/MODIS/16Day/Mosaic/
        output_ndvi: s:/WFP/MODIS/16Day/NDVI/
        output_evi: s:/WFP/MODIS/16Day/EVI/

CHIRPS:
    filenames:
        input_prefix: png_cli_chirps-v2.0
        input_extension: .tif
        output_prefix: png_cli_chirps-v2.0
        output_ext: .tif

    thresholds:
        precipitation_threshold: 0.5
        max_days_to_process: 6

run:
#    - process: CHIRPS
#      type: monthly
#      input_dir: S:/WFP2/IDN_GIS/01_Data/03_Regional/04_PNG/Rasters/Climate/Precipitation/CHIRPS/Monthly/ByYear
#      output_dir: S:/WFP2/IDN_GIS/01_Data/03_Regional/04_PNG/Rasters/Climate/Precipitation/CHIRPS/Monthly/Statistics_ByMonth
#      functions: [AVG, MIN, MAX, STD]

#    - process: CHIRPS
#      type: dekad
#      input_dir: S:/WFP2/IDN_GIS/01_Data/03_Regional/04_PNG/Rasters/Climate/Precipitation/CHIRPS/Dekad/ByDekad
#      output_dir: S:/WFP2/IDN_GIS/01_Data/03_Regional/04_PNG/Rasters/Climate/Precipitation/CHIRPS/Dekad/Statistics_ByDekad
#      functions: [AVG, MIN, MAX, STD]

#    - process: CHIRPS
#      type: seasonal
#      input_dir: S:/WFP2/IDN_GIS/01_Data/03_Regional/04_PNG/Rasters/Climate/Precipitation/CHIRPS/Monthly-3/BySeason
#      input_extension: .tiff
#      output_dir: S:/WFP2/IDN_GIS/01_Data/03_Regional/04_PNG/Rasters/Climate/Precipitation/CHIRPS/Monthly-3/Statistics_BySeason
#      functions: [AVG, MIN, MAX, STD]

    - process: MODIS
      type: temperature
      input_dir: S:/WFP2/IDN_GIS/01_Data/03_Regional/04_PNG/Rasters/Climate/Temperature/MODIS/MOD11C3/Average
      output_dir: S:/WFP2/IDN_GIS/01_Data/03_Regional/04_PNG/Rasters/Climate/Temperature/MODIS/MOD11C3/Statistics_byMonth
      output_prefix: png_cli_MOD11C3
      output_ext: .tif
      functions: [AVG]

#    - process: Analysis
#      type: rainfall_anomaly
#      current_file: s:/WFP2/IDN_GIS/01_Data/03_Regional/04_PNG/Rasters/Climate/Precipitation/CHIRPS/Monthly/ByYear/png_cli_chirps-v2.0.2015.12.tif
#      longterm_avg_file: s:/WFP2/IDN_GIS/01_Data/03_Regional/04_PNG/Rasters/Climate/Precipitation/CHIRPS/Monthly/Statistics_ByMonth/png_cli_chirps-v2.0.1981-2015.12.monthly.34yrs.avg.tif
#      output_file: s:/WFP2/IDN_GIS/05_Analysis/03_Early_Warning/Rainfall_Anomaly/png_cli_chirps-v2.0.2015.12.ratio_anom.tif

#    - process: Analysis
#      type: rainfall_anomaly
#      current_file: s:/WFP2/IDN_GIS/01_Data/03_Regional/04_PNG/Rasters/Climate/Precipitation/CHIRPS/Monthly-3/BySeason/png_cli_chirps-v2.0.2015.091011.tiff
#      longterm_avg_file: s:/WFP2/IDN_GIS/01_Data/03_Regional/04_PNG/Rasters/Climate/Precipitation/CHIRPS/Monthly-3/Statistics_BySeason/png_cli_chirps-v2.0.1981-2014.091011.avg.tif
#      output_file: s:/WFP2/IDN_GIS/05_Analysis/03_Early_Warning/Rainfall_Anomaly/png_cli_chirps-v2.0.2015.091011.ratio_anom.tif

#    - process: Analysis
#      type: TCI
#      current_file: S:/WFP2/IDN_GIS/01_Data/03_Regional/04_PNG/Rasters/Climate/Temperature/MODIS/MOD11C3/Average/png_cli_MOD11C3.A2015335.005.2016008055128.avg.tif
#      LST_max_file: S:/WFP2/IDN_GIS/01_Data/03_Regional/04_PNG/Rasters/Climate/Temperature/MODIS/MOD11C3/Statistics_byMonth/png_cli_MOD11C3.2000-2015.335.15yrs.max.tif
#      LST_min_file: S:/WFP2/IDN_GIS/01_Data/03_Regional/04_PNG/Rasters/Climate/Temperature/MODIS/MOD11C3/Statistics_byMonth/png_cli_MOD11C3.2000-2015.335.15yrs.min.tif
#      output_file: s:/WFP2/IDN_GIS/05_Analysis/03_Early_Warning/Temperature_Condition_Index/png_cli_MOD11C3.2015.335.tci.tif

#    - process: Analysis
#      type: TCI
#      current_file: S:/WFP2/IDN_GIS/01_Data/03_Regional/04_PNG/Rasters/Climate/Temperature/MODIS/MOD11C3/Average/png_cli_MOD11C3.A2015305.005.2015336235112.avg.tif
#      LST_max_file: S:/WFP2/IDN_GIS/01_Data/03_Regional/04_PNG/Rasters/Climate/Temperature/MODIS/MOD11C3/Statistics_byMonth/png_cli_MOD11C3.2000-2015.305.15yrs.max.tif
#      LST_min_file: S:/WFP2/IDN_GIS/01_Data/03_Regional/04_PNG/Rasters/Climate/Temperature/MODIS/MOD11C3/Statistics_byMonth/png_cli_MOD11C3.2000-2015.305.15yrs.min.tif
#      output_file: s:/WFP2/IDN_GIS/05_Analysis/03_Early_Warning/Temperature_Condition_Index/png_cli_MOD11C3.2015.305.tci.tif

#    - process: Analysis
#      type: TCI
#      current_file: S:/WFP2/IDN_GIS/01_Data/03_Regional/04_PNG/Rasters/Climate/Temperature/MODIS/MOD11C3/Average/png_cli_MOD11C3.A2015274.005.2015310140456.avg.tif
#      LST_max_file: S:/WFP2/IDN_GIS/01_Data/03_Regional/04_PNG/Rasters/Climate/Temperature/MODIS/MOD11C3/Statistics_byMonth/png_cli_MOD11C3.2000-2015.274.15yrs.max.tif
#      LST_min_file: S:/WFP2/IDN_GIS/01_Data/03_Regional/04_PNG/Rasters/Climate/Temperature/MODIS/MOD11C3/Statistics_byMonth/png_cli_MOD11C3.2000-2015.274.15yrs.min.tif
#      output_file: s:/WFP2/IDN_GIS/05_Analysis/03_Early_Warning/Temperature_Condition_Index/png_cli_MOD11C3.2015.274.tci.tif

#    - process: Analysis
#      type: VCI
#      current_file: S:/WFP2/IDN_GIS/01_Data/03_Regional/04_PNG/Rasters/Climate/Temperature/MODIS/MOD11C3/Average/png_cli_MOD11C3.A2015335.005.2016008055128.avg.tif
#      lst_max_file: S:/WFP2/IDN_GIS/01_Data/03_Regional/04_PNG/Rasters/Climate/Temperature/MODIS/MOD11C3/Statistics_byMonth/png_cli_MOD11C3.2000-2015.335.15yrs.max.tif
#      lst_min_file: S:/WFP2/IDN_GIS/01_Data/03_Regional/04_PNG/Rasters/Climate/Temperature/MODIS/MOD11C3/Statistics_byMonth/png_cli_MOD11C3.2000-2015.335.15yrs.min.tif
#      output_file: s:/WFP2/IDN_GIS/05_Analysis/03_Early_Warning/Temperature_Condition_Index/png_cli_MOD11C3.2015.335.tci.tif

